// Automatically generated by MockGen. DO NOT EDIT!
// Source: github.com/seven5/seven5 (interfaces: CookieMapper)

package mock

import (
	http "net/http"
	seven5 "github.com/seven5/seven5"
	gomock "code.google.com/p/gomock/gomock"
)

// Mock of CookieMapper interface
type MockCookieMapper struct {
	ctrl     *gomock.Controller
	recorder *_MockCookieMapperRecorder
}

// Recorder for MockCookieMapper (not exported)
type _MockCookieMapperRecorder struct {
	mock *MockCookieMapper
}

func NewMockCookieMapper(ctrl *gomock.Controller) *MockCookieMapper {
	mock := &MockCookieMapper{ctrl: ctrl}
	mock.recorder = &_MockCookieMapperRecorder{mock}
	return mock
}

func (_m *MockCookieMapper) EXPECT() *_MockCookieMapperRecorder {
	return _m.recorder
}

func (_m *MockCookieMapper) AssociateCookie(_param0 http.ResponseWriter, _param1 seven5.Session) {
	_m.ctrl.Call(_m, "AssociateCookie", _param0, _param1)
}

func (_mr *_MockCookieMapperRecorder) AssociateCookie(arg0, arg1 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "AssociateCookie", arg0, arg1)
}

func (_m *MockCookieMapper) CookieName() string {
	ret := _m.ctrl.Call(_m, "CookieName")
	ret0, _ := ret[0].(string)
	return ret0
}

func (_mr *_MockCookieMapperRecorder) CookieName() *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "CookieName")
}

func (_m *MockCookieMapper) RemoveCookie(_param0 http.ResponseWriter) {
	_m.ctrl.Call(_m, "RemoveCookie", _param0)
}

func (_mr *_MockCookieMapperRecorder) RemoveCookie(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "RemoveCookie", arg0)
}

func (_m *MockCookieMapper) Value(_param0 *http.Request) (string, error) {
	ret := _m.ctrl.Call(_m, "Value", _param0)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (_mr *_MockCookieMapperRecorder) Value(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "Value", arg0)
}
