// Automatically generated by MockGen. DO NOT EDIT!
// Source: github.com/seven5/seven5 (interfaces: DeploymentEnvironment)

package mock

import (
	gomock "code.google.com/p/gomock/gomock"
	seven5 "github.com/seven5/seven5"
)

// Mock of DeploymentEnvironment interface
type MockDeploymentEnvironment struct {
	ctrl     *gomock.Controller
	recorder *_MockDeploymentEnvironmentRecorder
}

// Recorder for MockDeploymentEnvironment (not exported)
type _MockDeploymentEnvironmentRecorder struct {
	mock *MockDeploymentEnvironment
}

func NewMockDeploymentEnvironment(ctrl *gomock.Controller) *MockDeploymentEnvironment {
	mock := &MockDeploymentEnvironment{ctrl: ctrl}
	mock.recorder = &_MockDeploymentEnvironmentRecorder{mock}
	return mock
}

func (_m *MockDeploymentEnvironment) EXPECT() *_MockDeploymentEnvironmentRecorder {
	return _m.recorder
}

func (_m *MockDeploymentEnvironment) GetAppValue(_param0 string) string {
	ret := _m.ctrl.Call(_m, "GetAppValue", _param0)
	ret0, _ := ret[0].(string)
	return ret0
}

func (_mr *_MockDeploymentEnvironmentRecorder) GetAppValue(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "GetAppValue", arg0)
}

func (_m *MockDeploymentEnvironment) GetQbsStore() *seven5.QbsStore {
	ret := _m.ctrl.Call(_m, "GetQbsStore")
	ret0, _ := ret[0].(*seven5.QbsStore)
	return ret0
}

func (_mr *_MockDeploymentEnvironmentRecorder) GetQbsStore() *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "GetQbsStore")
}

func (_m *MockDeploymentEnvironment) IsTest() bool {
	ret := _m.ctrl.Call(_m, "IsTest")
	ret0, _ := ret[0].(bool)
	return ret0
}

func (_mr *_MockDeploymentEnvironmentRecorder) IsTest() *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "IsTest")
}

func (_m *MockDeploymentEnvironment) MustAppValue(_param0 string) string {
	ret := _m.ctrl.Call(_m, "MustAppValue", _param0)
	ret0, _ := ret[0].(string)
	return ret0
}

func (_mr *_MockDeploymentEnvironmentRecorder) MustAppValue(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "MustAppValue", arg0)
}

func (_m *MockDeploymentEnvironment) Port() int {
	ret := _m.ctrl.Call(_m, "Port")
	ret0, _ := ret[0].(int)
	return ret0
}

func (_mr *_MockDeploymentEnvironmentRecorder) Port() *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "Port")
}

func (_m *MockDeploymentEnvironment) RedirectHost() string {
	ret := _m.ctrl.Call(_m, "RedirectHost")
	ret0, _ := ret[0].(string)
	return ret0
}

func (_mr *_MockDeploymentEnvironmentRecorder) RedirectHost() *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "RedirectHost")
}
