// Automatically generated by MockGen. DO NOT EDIT!
// Source: github.com/seven5/seven5 (interfaces: PageMapper)

package mock

import (
	gomock "code.google.com/p/gomock/gomock"
	seven5 "github.com/seven5/seven5"
)

// Mock of PageMapper interface
type MockPageMapper struct {
	ctrl     *gomock.Controller
	recorder *_MockPageMapperRecorder
}

// Recorder for MockPageMapper (not exported)
type _MockPageMapperRecorder struct {
	mock *MockPageMapper
}

func NewMockPageMapper(ctrl *gomock.Controller) *MockPageMapper {
	mock := &MockPageMapper{ctrl: ctrl}
	mock.recorder = &_MockPageMapperRecorder{mock}
	return mock
}

func (_m *MockPageMapper) EXPECT() *_MockPageMapperRecorder {
	return _m.recorder
}

func (_m *MockPageMapper) ErrorPage(_param0 seven5.OauthConnector, _param1 string) string {
	ret := _m.ctrl.Call(_m, "ErrorPage", _param0, _param1)
	ret0, _ := ret[0].(string)
	return ret0
}

func (_mr *_MockPageMapperRecorder) ErrorPage(arg0, arg1 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "ErrorPage", arg0, arg1)
}

func (_m *MockPageMapper) LoginLandingPage(_param0 seven5.OauthConnector, _param1 string, _param2 string) string {
	ret := _m.ctrl.Call(_m, "LoginLandingPage", _param0, _param1, _param2)
	ret0, _ := ret[0].(string)
	return ret0
}

func (_mr *_MockPageMapperRecorder) LoginLandingPage(arg0, arg1, arg2 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "LoginLandingPage", arg0, arg1, arg2)
}

func (_m *MockPageMapper) LogoutLandingPage(_param0 seven5.OauthConnector) string {
	ret := _m.ctrl.Call(_m, "LogoutLandingPage", _param0)
	ret0, _ := ret[0].(string)
	return ret0
}

func (_mr *_MockPageMapperRecorder) LogoutLandingPage(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "LogoutLandingPage", arg0)
}
