include $(GOROOT)/src/Make.inc

TARG=seven5_run.go
GOFILES=\
	seven5_run.go\

#if you want to try the demos of the raw layer of mongrel2 support, you need
#change the TARG and GOFILES in be either mongrel_raw(.go) or 
#mongrel_workers(.go)

include $(GOROOT)/src/Make.cmd
