// Automatically generated by MockGen. DO NOT EDIT!
// Source: env.go

package auth

import (
	gomock "code.google.com/p/gomock/gomock"
	http "net/http"
)

// Mock of DeploymentEnvironment interface
type MockDeploymentEnvironment struct {
	ctrl     *gomock.Controller
	recorder *_MockDeploymentEnvironmentRecorder
}

// Recorder for MockDeploymentEnvironment (not exported)
type _MockDeploymentEnvironmentRecorder struct {
	mock *MockDeploymentEnvironment
}

func NewMockDeploymentEnvironment(ctrl *gomock.Controller) *MockDeploymentEnvironment {
	mock := &MockDeploymentEnvironment{ctrl: ctrl}
	mock.recorder = &_MockDeploymentEnvironmentRecorder{mock}
	return mock
}

func (_m *MockDeploymentEnvironment) EXPECT() *_MockDeploymentEnvironmentRecorder {
	return _m.recorder
}

func (_m *MockDeploymentEnvironment) IsTest() bool {
	ret := _m.ctrl.Call(_m, "IsTest")
	ret0, _ := ret[0].(bool)
	return ret0
}

func (_mr *_MockDeploymentEnvironmentRecorder) IsTest() *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "IsTest")
}

func (_m *MockDeploymentEnvironment) Port() int {
	ret := _m.ctrl.Call(_m, "Port")
	ret0, _ := ret[0].(int)
	return ret0
}

func (_mr *_MockDeploymentEnvironmentRecorder) Port() *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "Port")
}

func (_m *MockDeploymentEnvironment) RedirectHost(_param0 string) string {
	ret := _m.ctrl.Call(_m, "RedirectHost", _param0)
	ret0, _ := ret[0].(string)
	return ret0
}

func (_mr *_MockDeploymentEnvironmentRecorder) RedirectHost(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "RedirectHost", arg0)
}

// Mock of PublicSettings interface
type MockPublicSettings struct {
	ctrl     *gomock.Controller
	recorder *_MockPublicSettingsRecorder
}

// Recorder for MockPublicSettings (not exported)
type _MockPublicSettingsRecorder struct {
	mock *MockPublicSettings
}

func NewMockPublicSettings(ctrl *gomock.Controller) *MockPublicSettings {
	mock := &MockPublicSettings{ctrl: ctrl}
	mock.recorder = &_MockPublicSettingsRecorder{mock}
	return mock
}

func (_m *MockPublicSettings) EXPECT() *_MockPublicSettingsRecorder {
	return _m.recorder
}

func (_m *MockPublicSettings) PublicSettingsHandler(n string) func(http.ResponseWriter, *http.Request) {
	ret := _m.ctrl.Call(_m, "PublicSettingsHandler", n)
	ret0, _ := ret[0].(func(http.ResponseWriter, *http.Request))
	return ret0
}

func (_mr *_MockPublicSettingsRecorder) PublicSettingsHandler(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "PublicSettingsHandler", arg0)
}

// Mock of ProjectFinder interface
type MockProjectFinder struct {
	ctrl     *gomock.Controller
	recorder *_MockProjectFinderRecorder
}

// Recorder for MockProjectFinder (not exported)
type _MockProjectFinderRecorder struct {
	mock *MockProjectFinder
}

func NewMockProjectFinder(ctrl *gomock.Controller) *MockProjectFinder {
	mock := &MockProjectFinder{ctrl: ctrl}
	mock.recorder = &_MockProjectFinderRecorder{mock}
	return mock
}

func (_m *MockProjectFinder) EXPECT() *_MockProjectFinderRecorder {
	return _m.recorder
}

func (_m *MockProjectFinder) ProjectFind(target string, projectName string, flavor FileFlavor) (string, error) {
	ret := _m.ctrl.Call(_m, "ProjectFind", target, projectName, flavor)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (_mr *_MockProjectFinderRecorder) ProjectFind(arg0, arg1, arg2 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "ProjectFind", arg0, arg1, arg2)
}
